# Generated by Django 4.2.9 on 2026-03-07 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_reconcile_student_promotion_history_table'),
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_compulsory', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='app.academicclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_subject_enrollments', to='app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='app.subject')),
            ],
            options={
                'db_table': 'app_studentsubjectenrollment',
                'ordering': ['academic_class_id', 'subject__name', 'student__student_name'],
                'indexes': [models.Index(fields=['academic_class', 'subject'], name='sse_class_subject_idx'), models.Index(fields=['student', 'academic_class'], name='sse_student_class_idx')],
                'unique_together': {('academic_class', 'student', 'subject')},
            },
        ),
    ]
