# Generated by Django 4.2.9 on 2026-03-07 17:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_reconcile_student_promotion_history_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secondary', '0002_studentsubjectenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondarycomputationpolicy',
            name='level',
            field=models.CharField(choices=[('LOWER_SECONDARY', 'Lower Secondary (S1-S4)'), ('UPPER_SECONDARY', 'Upper Secondary (S5-S6 / A-Level)')], default='LOWER_SECONDARY', max_length=30),
        ),
        migrations.CreateModel(
            name='ALevelSubjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('module_order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alevel_modules', to='app.subject')),
            ],
            options={
                'db_table': 'app_alevelsubjectmodule',
                'ordering': ['subject__name', 'module_order', 'code'],
                'unique_together': {('subject', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ALevelAssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('COURSEWORK', 'Coursework / SBA'), ('PRACTICAL', 'Practical'), ('PROJECT', 'Project'), ('WRITTEN_EXAM', 'Written Exam'), ('ORAL', 'Oral'), ('MODULAR_EXAM', 'Modular Exam'), ('OTHER', 'Other')], max_length=30)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('competency_code', models.CharField(blank=True, default='', max_length=30)),
                ('points_awarded', models.DecimalField(decimal_places=2, max_digits=6)),
                ('assessed_on', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alevel_assessments', to='app.academicyear')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='secondary.alevelsubjectmodule')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alevel_assessments_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alevel_assessments', to='app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alevel_assessments', to='app.subject')),
            ],
            options={
                'db_table': 'app_alevelassessmentrecord',
                'ordering': ['-assessed_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ALevelComponentWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('COURSEWORK', 'Coursework / SBA'), ('PRACTICAL', 'Practical'), ('PROJECT', 'Project'), ('WRITTEN_EXAM', 'Written Exam'), ('ORAL', 'Oral'), ('MODULAR_EXAM', 'Modular Exam'), ('OTHER', 'Other')], max_length=30)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_required', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alevel_component_weights', to='secondary.secondarycomputationpolicy')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alevel_component_weights', to='app.subject')),
            ],
            options={
                'db_table': 'app_alevelcomponentweight',
                'ordering': ['subject__name', 'component_type'],
                'unique_together': {('policy', 'subject', 'component_type')},
            },
        ),
        migrations.CreateModel(
            name='ALevelCompetencyScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('descriptor', models.CharField(max_length=120)),
                ('point_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('min_weighted_point', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_weighted_point', models.DecimalField(decimal_places=2, max_digits=6)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alevel_scales', to='secondary.secondarycomputationpolicy')),
            ],
            options={
                'db_table': 'app_alevelcompetencyscale',
                'ordering': ['display_order', '-min_weighted_point'],
                'unique_together': {('policy', 'code')},
            },
        ),
    ]
