# Generated by Django 4.2.9 on 2026-03-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_reconcile_student_promotion_history_table'),
        ('secondary', '0003_alter_secondarycomputationpolicy_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALevelSubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighted_point', models.DecimalField(decimal_places=2, max_digits=6)),
                ('final_competency', models.CharField(max_length=30)),
                ('final_descriptor', models.CharField(blank=True, max_length=255)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alevel_subject_results', to='app.academicyear')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alevel_subject_results', to='secondary.secondarycomputationpolicy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alevel_subject_results', to='app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alevel_subject_results', to='app.subject')),
            ],
            options={
                'db_table': 'app_alevelsubjectresult',
                'ordering': ['student_id', 'subject__name'],
                'unique_together': {('student', 'subject', 'academic_year')},
            },
        ),
    ]
