# Generated by Django 4.2.9 on 2026-10-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('grade_level', models.CharField(max_length=64)),
                ('class_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Enrolled'), ('inactive', 'Inactive'), ('warning', 'Warning'), ('overdue', 'Overdue'), ('review', 'Review')], default='active', max_length=32)),
                ('parent_name', models.CharField(blank=True, default='', max_length=128)),
                ('parent_phone', models.CharField(blank=True, default='', max_length=32)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='FeeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.CharField(max_length=64, unique=True)),
                ('term', models.CharField(default='Term 1', max_length=32)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('partial', 'Partial'), ('settled', 'Settled'), ('overdue', 'Overdue')], default='partial', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_ledgers', to='backend.student')),
            ],
            options={
                'verbose_name': 'Fee Ledger',
                'verbose_name_plural': 'Fee Ledgers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('assessment_type', models.CharField(default='exam', max_length=64)),
                ('academic_year', models.CharField(default='2025', max_length=32)),
                ('term', models.CharField(default='Term 1', max_length=32)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('grade', models.CharField(blank=True, default='', max_length=8)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_matrices', to='backend.student')),
            ],
            options={
                'verbose_name': 'Grade Matrix',
                'verbose_name_plural': 'Grade Matrices',
                'ordering': ['student__last_name', 'subject', 'term'],
                'unique_together': {('student', 'subject', 'assessment_type', 'academic_year', 'term')},
            },
        ),
    ]
