# Generated by Django 4.2.9 on 2026-06-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_student_number_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Inactive', 'Inactive'), ('Retired', 'Retired')], default='Active', max_length=20),
        ),
    ]
