# Generated by Django 4.2.9 on 2026-07-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_reportcycleremark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcycleremark',
            name='class_teacher_remark',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
