# Generated by Django 4.2.9 on 2026-08-08 08:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def use_legacy_mysql_engine(apps, schema_editor):
    """Match legacy MyISAM tables before creating related tables."""
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT ENGINE FROM information_schema.TABLES "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'app_student'"
        )
        row = cursor.fetchone()
        if row and (row[0] or "").upper() == "MYISAM":
            cursor.execute("SET SESSION default_storage_engine = MyISAM")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0112_alter_reportcycleremark_class_teacher_remark'),
    ]

    operations = [
        migrations.RunPython(use_legacy_mysql_engine, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('birthdate', models.DateField()),
                ('nationality', models.CharField(blank=True, max_length=30)),
                ('religion', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('previous_school', models.CharField(blank=True, max_length=150)),
                ('guardian', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('review', 'Under review'), ('shortlisted', 'Shortlisted'), ('assessment', 'Assessment'), ('interview', 'Interview'), ('waitlisted', 'Wait-listed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applying_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='app.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admission_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=30)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('publisher', models.CharField(blank=True, max_length=150)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shelf_location', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='LibraryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=40, unique=True)),
                ('barcode', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_loan', 'On loan'), ('reserved', 'Reserved'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('repair', 'Under repair'), ('withdrawn', 'Withdrawn')], default='available', max_length=20)),
                ('condition_notes', models.CharField(blank=True, max_length=255)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='app.librarybook')),
            ],
            options={
                'ordering': ('accession_number',),
            },
        ),
        migrations.CreateModel(
            name='LibraryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=20, unique=True)),
                ('maximum_books', models.PositiveSmallIntegerField(default=3)),
                ('loan_days', models.PositiveSmallIntegerField(default=14)),
                ('renewal_limit', models.PositiveSmallIntegerField(default=1)),
                ('daily_fine', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('block_when_overdue', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('renewals', models.PositiveSmallIntegerField(default=0)),
                ('return_condition', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='app.librarycopy')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_library_loans', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_library_loans', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='library_loans', to='app.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='library_loans', to='app.student')),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.AddField(
            model_name='librarybook',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='app.librarycategory'),
        ),
        migrations.CreateModel(
            name='LibraryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('copy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.librarycopy')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='app.libraryloan')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdmissionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='app.admissionapplication')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-changed_at',),
            },
        ),
        migrations.CreateModel(
            name='AdmissionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opens_on', models.DateField()),
                ('closes_on', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.academicyear')),
            ],
            options={
                'ordering': ('-opens_on',),
            },
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='app.admissioncycle'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='enrolled_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_admission_application', to='app.student'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='preferred_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.stream'),
        ),
        migrations.CreateModel(
            name='ParentPortalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', 'created_at'], name='parent_audit_action_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_academics', models.BooleanField(default=True)),
                ('can_view_finance', models.BooleanField(default=True)),
                ('can_view_attendance', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(default=True)),
                ('temporary_password_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_accesses', to='app.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_accesses', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_parent_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='parent_access_user_active_idx'), models.Index(fields=['student', 'is_active'], name='parent_student_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='parentaccess',
            constraint=models.UniqueConstraint(fields=('user', 'student'), name='unique_parent_user_student_access'),
        ),
        migrations.AddIndex(
            model_name='libraryloan',
            index=models.Index(fields=['due_at', 'returned_at'], name='library_loan_due_return_idx'),
        ),
        migrations.AddConstraint(
            model_name='libraryloan',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('staff__isnull', True), ('student__isnull', False)), models.Q(('staff__isnull', False), ('student__isnull', True)), _connector='OR'), name='library_loan_exactly_one_borrower'),
        ),
        migrations.AddConstraint(
            model_name='libraryloan',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('copy',), name='unique_active_library_copy_loan'),
        ),
        migrations.AddConstraint(
            model_name='admissioncycle',
            constraint=models.UniqueConstraint(fields=('name', 'academic_year'), name='unique_admission_cycle_year'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['cycle', 'status'], name='admission_cycle_status_idx'),
        ),
    ]
