# Generated by Django 4.2.9 on 2026-08-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0113_admissionapplication_librarybook_librarycategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Bursar', 'Bursar'), ('Director of Studies', 'Director of Studies'), ('Head master', 'Head master'), ('Class Teacher', 'Class Teacher'), ('Support Staff', 'Support Staff'), ('Admissions Officer', 'Admissions Officer'), ('Librarian', 'Librarian'), ('Library Assistant', 'Library Assistant')], max_length=50, unique=True),
        ),
    ]
