# Generated by Django 4.2.9 on 2026-08-08 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def use_legacy_mysql_engine(apps, schema_editor):
    """Match the library tables created on a legacy MyISAM database."""
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT ENGINE FROM information_schema.TABLES "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'app_libraryloan'"
        )
        row = cursor.fetchone()
        if row and (row[0] or "").upper() == "MYISAM":
            cursor.execute("SET SESSION default_storage_engine = MyISAM")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0115_alter_admissionapplication_address_and_more'),
    ]

    operations = [
        migrations.RunPython(use_legacy_mysql_engine, migrations.RunPython.noop),
        migrations.CreateModel(
            name='LibraryFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('overdue', 'Overdue'), ('lost', 'Lost item'), ('damaged', 'Damaged item')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('outstanding', 'Outstanding'), ('paid', 'Paid'), ('waived', 'Waived')], default='outstanding', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_library_fines', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='app.libraryloan')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_library_fines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-assessed_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='libraryfine',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='library_fine_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='libraryfine',
            constraint=models.UniqueConstraint(fields=('loan', 'reason'), name='unique_library_fine_reason_per_loan'),
        ),
    ]
