"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

from decouple import config

import pymysql

pymysql.install_as_MySQLdb()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # 'unfold',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'crispy_forms',
    'crispy_bootstrap4',
    'widget_tweaks',
    'app',
   
] 

CRISPY_TEMPLATE_PACK = "bootstrap4"


MIDDLEWARE = [
    'core.middleware.DatabaseConnectionCleanupMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'app.middleware.parent_isolation.ParentPortalIsolationMiddleware',
    'app.middleware.request_user.RequestUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware.update_jazzmin.UpdateJazzminMiddleware',
    'core.middleware.AutoLogoutMiddleware',

]

ROOT_URLCONF = 'core.urls'
CSRF_FAILURE_VIEW = 'app.views.errors.csrf_failure'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.school_settings'
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DEFAULT_DB_ENGINE = 'django.db.backends.mysql'
DEFAULT_DB_NAME = 'bayezieu_schooldb'
DEFAULT_DB_USER = 'bayezieu_bayan_user'
DEFAULT_DB_PASSWORD = '@bayan%dbuser'
DEFAULT_DB_HOST = '127.0.0.1'
DEFAULT_DB_PORT = '3306'
DEFAULT_SQLITE_NAME = str(BASE_DIR / 'db.sqlite3')
DEFAULT_CACHE_BACKEND = 'django.core.cache.backends.filebased.FileBasedCache'
DEFAULT_CACHE_LOCATION = str(BASE_DIR / 'tmp' / 'django-cache')
TRUTHY_VALUES = {'1', 'true', 'yes', 'on'}
FALSY_VALUES = {'0', 'false', 'no', 'off'}


def config_bool(name, default=False):
    raw_value = config(name, default=None)
    if raw_value is None:
        return default
    if isinstance(raw_value, bool):
        return raw_value

    normalized = str(raw_value).strip().lower()
    if normalized in TRUTHY_VALUES:
        return True
    if normalized in FALSY_VALUES:
        return False
    return default


def build_database_settings():
    use_sqlite = config_bool('USE_SQLITE', default=False)
    db_engine = config(
        'DB_ENGINE',
        default='django.db.backends.sqlite3' if use_sqlite else DEFAULT_DB_ENGINE,
    )

    if use_sqlite or db_engine == 'django.db.backends.sqlite3':
        sqlite_name = config('SQLITE_NAME', default=DEFAULT_SQLITE_NAME)
        return {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': sqlite_name,
            }
        }

    db_config = {
        'ENGINE': db_engine,
        'NAME': config('DB_NAME', default=DEFAULT_DB_NAME),
        'USER': config('DB_USER', default=DEFAULT_DB_USER),
        'PASSWORD': config('DB_PASSWORD', default=DEFAULT_DB_PASSWORD),
        'HOST': config('DB_HOST', default=DEFAULT_DB_HOST),
        'PORT': config('DB_PORT', default=DEFAULT_DB_PORT),
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=0, cast=int),
        'CONN_HEALTH_CHECKS': config_bool('DB_CONN_HEALTH_CHECKS', default=False),
    }

    if db_engine == 'django.db.backends.mysql':
        db_options = {
            'charset': config('DB_CHARSET', default='utf8mb4'),
            'use_unicode': True,
        }
        init_command = config('DB_INIT_COMMAND', default="SET time_zone = '+03:00'")
        unix_socket = config('DB_SOCKET', default='').strip()

        if init_command:
            db_options['init_command'] = init_command
        if unix_socket and os.path.exists(unix_socket):
            db_options['unix_socket'] = unix_socket

        db_config['OPTIONS'] = db_options

    return {'default': db_config}


DATABASES = build_database_settings()

# Schools can temporarily bypass the DOS sampling workflow. Submitted marks
# are immediately released to reports when this is disabled.
RESULT_VERIFICATION_ENABLED = config_bool('RESULT_VERIFICATION_ENABLED', default=False)

# New production modules are deployed dark and enabled individually after their
# migrations, permissions and pilot data have been verified.
PARENT_PORTAL_ENABLED = config_bool('PARENT_PORTAL_ENABLED', default=False)
ADMISSIONS_ENABLED = config_bool('ADMISSIONS_ENABLED', default=False)
LIBRARY_ENABLED = config_bool('LIBRARY_ENABLED', default=False)
PUBLIC_ADMISSIONS_ENABLED = config_bool('PUBLIC_ADMISSIONS_ENABLED', default=False)
PUBLIC_ADMISSION_MAX_SUBMISSIONS = config('PUBLIC_ADMISSION_MAX_SUBMISSIONS', default=5, cast=int)
PUBLIC_ADMISSION_RATE_SECONDS = config('PUBLIC_ADMISSION_RATE_SECONDS', default=3600, cast=int)
PARENT_LOGIN_MAX_ATTEMPTS = config('PARENT_LOGIN_MAX_ATTEMPTS', default=5, cast=int)
PARENT_LOGIN_LOCK_SECONDS = config('PARENT_LOGIN_LOCK_SECONDS', default=900, cast=int)
PARENT_TEMP_PASSWORD_HOURS = config('PARENT_TEMP_PASSWORD_HOURS', default=24, cast=int)


CACHES = {
    'default': {
        'BACKEND': config('CACHE_BACKEND', default=DEFAULT_CACHE_BACKEND),
        'LOCATION': config('CACHE_LOCATION', default=DEFAULT_CACHE_LOCATION),
        'TIMEOUT': config('CACHE_TIMEOUT', default=300, cast=int),
    }
}

DASHBOARD_CACHE_TIMEOUT = config('DASHBOARD_CACHE_TIMEOUT', default=90, cast=int)
NAV_CONTEXT_CACHE_TIMEOUT = config('NAV_CONTEXT_CACHE_TIMEOUT', default=45, cast=int)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')  
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'


#Ssessions
SESSION_COOKIE_AGE = 1800  # 30 minutes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_ENGINE = config(
    'SESSION_ENGINE',
    default='django.contrib.sessions.backends.cached_db',
)
SESSION_CACHE_ALIAS = config('SESSION_CACHE_ALIAS', default='default')
SESSION_SAVE_EVERY_REQUEST = config_bool('SESSION_SAVE_EVERY_REQUEST', default=False)
SESSION_ACTIVITY_SAVE_EVERY = config('SESSION_ACTIVITY_SAVE_EVERY', default=60, cast=int)


DEV_TUNNEL_URL = "https//:bayan-learningcenter.com"  

# Email Configuration for SMTP (Using Gmail)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "bayern-learningcenter.com"
EMAIL_PORT = 465 
EMAIL_USE_SSL = True
EMAIL_HOST_USER = "bayan-learningcenter@bayern-learningcenter.com"
EMAIL_HOST_PASSWORD = "Mypp3[xD_Vdi" 
DEFAULT_FROM_EMAIL = "bayan-learningcenter@bayern-learningcenter.com"


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler'
        },
        'file':{
            'class': 'logging.FileHandler',
            'filename': 'general.log',
            'formatter': 'verbose'
        }
    },
    'loggers':{
        '': {
            'handlers': ['console', 'file'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO')
        }
    },
    'formatters':{
        'verbose': {
            'format': '{asctime} ({levelname}) - {name} {message}',
            'style': '{' #str.format
        }
    }
    
}

USER_ROLE_PREFIXES = {
    'Admin': 'Admin-',
    'Teacher': 'Teacher-',
    'Bursar': 'bursar-',
    'Director of studies': 'Dos-',
    'Head master': 'Hm-',
    'class Teacher': 'Class-Teacher-',
}



# admin dashboard settings
JAZZMIN_SETTINGS = {
    "site_title": "Bayan Learning Center Admin",
    "site_header": "Bayan Learning Center Administration",
    "site_brand": "Bayan Learning Center",
    "custom_css": "css/rainbow.css",  # Overridden per-request by UpdateJazzminMiddleware
    "site_logo": "images/user.png",
    "site_logo_classes": "brand-image img-circle elevation-3",
    "site_icon": "images/favicon.ico",
    "welcome_sign": "Welcome to Bayan Learning Center Admin",
    "copyright": "UgaCloud 2025",
   

    # Quick global search
    "search_model": ["auth.User", "auth.Group"],

    # Navigation
    "show_sidebar": True,
    "navigation_expanded": True,
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"app": "app"},
        {"model": "auth.User"},
        {"name": "WebApp", "url": "https://bayan-learningcenter.com", "icon": "fas fa-globe", "new_window": True},
    ],
    

    # Icons to improve scannability
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
    },

    # Forms and relations UX
    "related_modal_active": True,
    "changeform_format": "vertical_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible"},

    # Language / misc
    "language_chooser": False,
    "show_ui_builder": False,  # keep off in production

    # Dashboard recent actions
    "recent_actions": {
        "icon": "fas fa-history",
        "title": "Recent Activities",
        "card_class": "card-primary",
        "show_scroll_bar": True,
    },

    # Non-intrusive overrides (served via {% static %})
    # "custom_css": "css/custom_overrides.css",
    # "custom_js": "build/js/custom.js",
}


JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",                     # Base theme (light)
    "dark_mode_theme": None,
    "theme_condition": "always",

    # Layout
    "navbar": "navbar-primary navbar-dark",   # Dark blue top bar
    "sidebar": "sidebar-dark-primary",        # Dark sidebar (deep blue)
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "footer_fixed": False,
    "actions_sticky_top": True,

    # Buttons
    "button_classes": {
        "primary": "btn btn-primary",
        "secondary": "btn btn-outline-secondary",
        "info": "btn btn-info",
        "warning": "btn btn-warning",
        "danger": "btn btn-danger",
        "success": "btn btn-success",
    },

    # UX polish
    "body_small_text": False,
    "brand_small_text": False,
    "sidebar_nav_small_text": False,
    "no_navbar_border": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_child_indent": True,
}
