# Generated by ChatGPT for safe subject-allocation deactivation.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0106_attendance_unmarked_submitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsubjectallocation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
