# Generated by Django 4.2.9 on 2026-08-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0114_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='guardian',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='nationality',
            field=models.CharField(choices=[('Ugandan', 'Ugandan'), ('Kenyan', 'Kenyan'), ('Tanzanian', 'Tanzanian'), ('Rwanda', 'Rwanda'), ('South Sudan', 'South Sudan'), ('Burundi', 'Burundi'), ('Somali', 'Somali')], max_length=30),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='religion',
            field=models.CharField(choices=[('Muslim', 'Muslim'), ('Protestant', 'Protestant'), ('Catholic', 'Catholic'), ('Adventist', 'Adventist'), ('Others', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='student_name',
            field=models.CharField(max_length=50),
        ),
    ]
