# Generated by Django 4.2.9 on 2026-08-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0116_libraryfine_libraryfine_library_fine_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='privacy_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal'), ('public', 'Online application')], default='internal', max_length=20),
        ),
    ]
