# Generated by Django 4.2.9 on 2026-08-08 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def use_legacy_mysql_engine(apps, schema_editor):
    """Match legacy MyISAM tables before creating parent portal tables."""
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT ENGINE FROM information_schema.TABLES "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'app_student'"
        )
        row = cursor.fetchone()
        if row and (row[0] or "").upper() == "MYISAM":
            cursor.execute("SET SESSION default_storage_engine = MyISAM")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0117_admissionapplication_privacy_consent_at_and_more'),
    ]

    operations = [
        migrations.RunPython(use_legacy_mysql_engine, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'All Staff'), ('parents', 'Parents'), ('teachers', 'Teachers'), ('head', 'Head Teacher'), ('bursar', 'Bursar'), ('dos', 'Director of Studies'), ('class_teacher', 'Class Teacher'), ('class_stream', 'Class Stream Teachers')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[('all', 'All Staff'), ('parents', 'Parents'), ('teachers', 'Teachers'), ('head', 'Head Teacher'), ('bursar', 'Bursar'), ('dos', 'Director of Studies'), ('class_teacher', 'Class Teacher'), ('class_stream', 'Class Stream Teachers')], default='all', max_length=20),
        ),
        migrations.CreateModel(
            name='ParentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_conversations', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_conversations', to='app.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_conversations', to='app.student')),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_conversation', to='app.messagethread')),
            ],
            options={
                'ordering': ('-thread__updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ParentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('source_key', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_notifications', to='app.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'read_at', 'created_at'], name='parent_notice_read_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='parentnotification',
            constraint=models.UniqueConstraint(fields=('user', 'source_key'), name='unique_parent_notification_source'),
        ),
        migrations.AddConstraint(
            model_name='parentconversation',
            constraint=models.UniqueConstraint(fields=('parent', 'student', 'staff'), name='unique_parent_student_staff_conversation'),
        ),
    ]
