from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0124_expand_blob_media_paths"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLifecycleEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("active", "Active"), ("transferred", "Transferred"), ("left", "Left school"), ("graduated", "Graduated"), ("reactivated", "Reactivated")], max_length=20)),
                ("reason", models.TextField(blank=True)),
                ("effective_date", models.DateField(default=django.utils.timezone.localdate)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("from_class", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="student_lifecycle_from", to="app.class")),
                ("from_stream", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="student_lifecycle_from_stream", to="app.stream")),
                ("recorded_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lifecycle_events", to="app.student")),
                ("to_class", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="student_lifecycle_to", to="app.class")),
                ("to_stream", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="student_lifecycle_to_stream", to="app.stream")),
            ],
            options={"ordering": ("-effective_date", "-created_at")},
        ),
        migrations.AddIndex(model_name="studentlifecycleevent", index=models.Index(fields=["student", "status", "effective_date"], name="student_lifecycle_idx")),
        migrations.CreateModel(
            name="StudentNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(choices=[("general", "General"), ("discipline", "Discipline"), ("welfare", "Welfare"), ("academic", "Academic")], default="general", max_length=20)),
                ("note", models.TextField()),
                ("is_private", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="profile_notes", to="app.student")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="StaffContract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contract_type", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("document", models.FileField(blank=True, max_length=500, upload_to="Staff/Contracts")),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("staff", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contracts", to="app.staff")),
            ],
            options={"ordering": ("-start_date", "-id")},
        ),
        migrations.CreateModel(
            name="StaffLeave",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("leave_type", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("staff", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leave_requests", to="app.staff")),
            ],
            options={"ordering": ("-start_date",)},
        ),
        migrations.CreateModel(
            name="StaffSalaryHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("effective_from", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("recorded_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("staff", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="salary_history", to="app.staff")),
            ],
            options={"ordering": ("-effective_from", "-id")},
        ),
        migrations.AddConstraint(model_name="staffsalaryhistory", constraint=models.CheckConstraint(check=models.Q(("amount__gte", 0)), name="staff_salary_history_nonnegative")),
        migrations.CreateModel(
            name="StaffPerformanceNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("note", models.TextField()),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("review_date", models.DateField(default=django.utils.timezone.localdate)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("staff", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="performance_notes", to="app.staff")),
            ],
            options={"ordering": ("-review_date", "-id")},
        ),
        migrations.CreateModel(
            name="AdmissionRequirement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("is_required", models.BooleanField(default=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("application", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="requirements", to="app.admissionapplication")),
                ("completed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("id",)},
        ),
        migrations.AddConstraint(model_name="admissionrequirement", constraint=models.UniqueConstraint(fields=("application", "name"), name="unique_admission_requirement")),
        migrations.CreateModel(
            name="PaymentReversal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.TextField()),
                ("reversed_at", models.DateTimeField(auto_now_add=True)),
                ("payment", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="reversal", to="app.payment")),
                ("reversed_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-reversed_at",)},
        ),
        migrations.CreateModel(
            name="FeeRefund",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.TextField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("paid", "Paid")], default="pending", max_length=20)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_fee_refunds", to=settings.AUTH_USER_MODEL)),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="refunds", to="app.payment")),
                ("requested_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_fee_refunds", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-requested_at",)},
        ),
        migrations.CreateModel(
            name="StudentAccountEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_type", models.CharField(choices=[("opening_balance", "Opening balance"), ("credit_note", "Credit note"), ("refund", "Refund"), ("reversal", "Payment reversal")], max_length=30)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reference", models.CharField(max_length=80, unique=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bill", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="account_entries", to="app.studentbill")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="account_entries", to="app.student")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="ResultPublication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("academic_class", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="result_publication", to="app.academicclass")),
                ("locked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="locked_result_publications", to=settings.AUTH_USER_MODEL)),
                ("published_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="published_result_publications", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("channel", models.CharField(choices=[("sms", "SMS"), ("email", "Email"), ("both", "SMS + Email")], max_length=10)),
                ("subject", models.CharField(blank=True, max_length=180)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(choices=[("sms", "SMS"), ("email", "Email"), ("both", "SMS + Email")], max_length=10)),
                ("subject", models.CharField(blank=True, max_length=180)),
                ("body", models.TextField()),
                ("audience_label", models.CharField(blank=True, max_length=120)),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("processing", "Processing"), ("sent", "Sent"), ("partial", "Partially sent"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="queued", max_length=20)),
                ("estimated_cost", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("actual_cost", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="OutboundDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipient_name", models.CharField(blank=True, max_length=150)),
                ("destination", models.CharField(max_length=254)),
                ("channel", models.CharField(choices=[("sms", "SMS"), ("email", "Email")], max_length=10)),
                ("consented", models.BooleanField(default=True)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("sent", "Sent"), ("delivered", "Delivered"), ("failed", "Failed"), ("skipped", "Skipped")], default="queued", max_length=20)),
                ("provider_reference", models.CharField(blank=True, max_length=160)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="app.outboundmessage")),
            ],
            options={"ordering": ("message_id", "id")},
        ),
        migrations.AddIndex(model_name="outbounddelivery", index=models.Index(fields=["status", "channel"], name="outbound_delivery_status_idx")),
    ]
